[global]
server_url = "ws://localhost:9900"
service_token = "service_secret_token_12345"

[services.echo]
enabled = true

[services.weather]
enabled = true
# Heidelberg, Germany
latitude = 49.37463969001847
longitude = 8.662844312005102
print_hour = 8
print_minute = 0

[services.chesspuzzle]
enabled = true
print_hour = 8
print_minute = 0

[services.music]
enabled = true
